language: python
python:
  - "3.9"
cache: pip
before_install:
  - curl https://eu.ftp.opendatasoft.com/bmoreau/test_ttl_data_dumps.zip -L -o ttl_data_dumps.zip
  - unzip -o ttl_data_dumps.zip
  - rm ttl_data_dumps.zip
  - rm -r __MACOSX/
  - touch chatbot_app/local_settings.py
  - echo "SECRET_KEY = '<SECRET_KEY>'" >> chatbot_app/local_settings.py
install:
  - pip install -r requirements.txt
  - docker-compose up -d
  - docker-compose ps
  - docker-compose logs -f &
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - python -m scripts.bulk_load
before_script:
  - sleep 10
  - wget -q -O - http://127.0.0.1:9200/rdf_types/_search
  - wget -q -O - http://127.0.0.1:9200/rdfs_labels/_search
script:
  - python -m pytest tests/