language: python
python:
  - "3.6"
cache: pip
before_install:
  - docker-compose up -d
  - curl https://eu.ftp.opendatasoft.com/bmoreau/test_ttl_data_dumps.zip -L -o ttl_data_dumps.zip
  - unzip -o ttl_data_dumps.zip
  - rm ttl_data_dumps.zip
  - rm -r __MACOSX/
  - touch chatbot_app/local_settings.py
  - echo "SECRET_KEY = '<SECRET_KEY>'" >> chatbot_app/local_settings.py
install:
  - pip install -r requirements.txt
  - python -m scripts.bulk_load
script:
  - python -m pytest tests/