<template>
<div  id="inersidepanel" class="intro animated" :class="{ 'fadeIn delay-05s': !fadeoutpanel, 'fadeOut': fadeoutpanel}" v-if="!appstarted">
  <h1>{{ title }}</h1>
  <ul>
    <li>
      <span>1.</span>Ask <a href="mailto:support@opendatasoft.com?Subject=semantic metadata">support</a> to enable metadata templates on your domain
    </li>
    <li>
      <span>2.</span>You will have a new "Semantic Metadata" tab in the "Information" tab of your dataset
    </li>
    <li>
      <span>3.</span>In the "Semantic Metadata" tab, you will be able to paste the RML mapping generated by the Semanticbot
    </li>
    <li>
    <small>
      <i>
        Submitted data are subject to <a href="https://legal.opendatasoft.com/en_FR/privacy-policy.html">Opendatasoft’s Privacy Policy</a>
      </i>
    </small>
    </li>
  </ul>
  <button class="btn btn-primary" v-on:click="startApp">I understand</button>
  
</div>

</template>

<script>
export default {
  name: 'Intro',
  data: function () {
    return {
      title: 'If it’s the first time, please activate semantic metadata on your domain',
      appstarted: false,
      fadeoutpanel: false
}
  },
  methods: {
    startApp: function (event) {
      this.fadeoutpanel = true
      setTimeout(()=>{
        this.$root.$emit('appstartedEvent', true);
      },1000);
      
    }
  },
  mounted: function () { 
      this.$root.$on('appstartedEvent', (appstartedstate) => { 
        this.appstarted = appstartedstate;
      })
  }
}
</script>

<style lang="scss">

</style>
