name: build-python
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
#          cache: npm

      - name: Setup pip
        uses: actions/setup-python@v3
        with:
          python-version: '3.6'
#          cache: pip

      - name: Setup js dependencies
        run: yarn install

      - name: Install pybind11
        run: pip install pybind11==2.2.4

      - name: Setup python dependencies
        run: pip install -r requirements.txt

      - name: Prepare tests
        run: echo "SECRET_KEY = '<SECRET_KEY>'" > chatbot_app/local_settings.py

      - name: Run Tests
        run: python -m pytest tests/

#  delivery:
#    runs-on: ubuntu-latest
#    needs:
#      - build-test
#
#    steps:
#      - name: Setup docker
#        uses: actions/setup-docker@v3

